targets:
  $default:
    sources:
      - lib/**
      - schema.json
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/graphql_api.dart
              schema: lib/schema.json
              queries_glob: lib/**.graphql
              add_query_prefix: true
              resolve_type_field: __typename
