name: gql_example_flutter
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  gql_link: ^0.2.1
  gql_http_link: ^0.2.2
  gql_client: ^0.0.2
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  get_it: ^3.1.0
dev_dependencies:
  build_runner: ^1.0.0
  gql_pedantic: ^1.0.0
  gql_build: ^0.0.2
  flutter_test:
    sdk: flutter
# Use latest until new version is published
dependency_overrides:
  gql_build:
    git:
      url: git://github.com/gql-dart/gql.git
      path: gql_build
  gql_code_builder:
    git:
      url: git://github.com/gql-dart/gql.git
      path: gql_code_builder
flutter:
  uses-material-design: true
