name: gql_cache_example
version: 0.0.1
description: Example usage for gql_cache
author: Sat Mandir Khalsa

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  gql_cache:
    path: ../
  hive: "^1.1.1"
  artemis: "^2.1.0+1"
  json_serializable: ^3.0.0
  equatable: ^0.6.1
  gql: ^0.11.1

dev_dependencies:
  test: ^1.9.4
  build_runner: ^1.6.7
  mobx_codegen: ^0.3.9+1
