builders:
  req_builder:
    import: "package:gql_client/src/req_builder/req_builder.dart"
    builder_factories: ["reqBuilder"]
    build_extensions: { ".graphql": [".req.gql.dart"] }
    auto_apply: none
    build_to: source
