name: ferry

packages:
  - packages/**
  - examples/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  build:
    exec: dart pub run build_runner build --delete-conflicting-outputs
    select-package:
      depends-on: build_runner
