name: gql_client
version: 0.1.2
description: GraphQL Client for Dart
homepage: https://github.com/smkhalsa/gql_client
repository: https://github.com/smkhalsa/gql_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  hive: ^1.3.0
  rxdart: ^0.23.1
  normalize: ^0.1.1
  uuid: ^2.0.4
  gql: ^0.12.0
  gql_link: ^0.2.2
  gql_exec: ^0.2.0
  gql_build: ^0.0.3
  built_collection: ^4.3.2
  built_value: ^7.0.9
  code_builder: ^3.2.1
  build: ^1.2.2

dev_dependencies:
  test: ^1.9.4
  mockito: ^4.1.1
  build_runner: ^1.6.7
  build_test: ^0.10.12+1
  built_value_generator: ^7.0.9
