name: ferry
version: 0.3.1
description: GraphQL Client for Dart
homepage: https://github.com/gql-dart/ferry
repository: https://github.com/gql-dart/ferry

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.1.8
  hive: ^1.3.0
  rxdart: ^0.23.1
  normalize: ^0.1.1
  gql: ^0.12.0
  gql_link: ^0.2.2
  gql_exec: ^0.2.0
  gql_build: ^0.0.10
  gql_code_builder: ^0.0.9
  built_collection: ^4.3.2
  code_builder: ^3.2.1
  build: ^1.2.2
  collection: ^1.14.11

dev_dependencies:
  test: ^1.9.4
  mockito: ^4.1.1
  build_runner: ^1.6.7
  build_test: ^0.10.12+1
