name: pokemon_explorer
version: 1.0.1
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  gql_link: ^0.3.0
  gql_http_link: ^0.2.9
  ferry: ^0.4.0
  ferry_generator:
    path: ../../ferry_generator
  ferry_hive_store:
    path: ../../ferry_hive_store
  ferry_flutter:
    path: ../../ferry_flutter
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  get_it: ^4.0.2
  flutter: 
    sdk: flutter
dev_dependencies: 
  build_runner: ^1.10.0
  gql_pedantic: ^1.0.2
  gql_build: ^0.0.11
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
