name: pokemon_explorer
version: 1.0.1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  gql_link: ^0.3.0
  gql_http_link: ^0.2.2
  ferry: ^0.4.0
  ferry_hive_store: ^0.1.0
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  get_it: ^3.1.0
dev_dependencies:
  build_runner: ^1.9.0
  gql_pedantic: ^1.0.0
  gql_build: ^0.0.10
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

depenency_overrides:
  ferry:
    path: ../../
  ferry_hive_store:
    path: ../../../ferry_hive_store
  ferry_store:
    path: ../../../ferry_store
