name: ferry_hive_store
version: 0.1.0
description: Hive-based Store implementation for Ferry GraphQL client
homepage: https://github.com/gql-dart/ferry/tree/master/ferry_hive_store
repository: https://github.com/gql-dart/ferry

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  hive: ^1.3.0
  ferry_store: ^0.1.0

dev_dependencies:
  test: ^1.9.4

dependency_overrides:
  ferry_store:
    path: ../ferry_store
