name: normalize
version: 0.2.0
description: Normalization and denormalization of GraphQL responses in Dart
homepage: https://github.com/gql-dart/ferry/tree/master/normalize
repository: https://github.com/gql-dart/ferry

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  gql: ^0.12.3

dev_dependencies:
  test: ^1.14.3
