name: ferry_flutter
version: 0.1.0
description: Flutter widgets for the Ferry GraphQL client
homepage: https://github.com/gql-dart/ferry/tree/master/ferry_flutter
repository: https://github.com/gql-dart/ferry

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  ferry: ^0.3.1+2
  gql_exec: ^0.2.4

dev_dependencies:
  test: ^1.9.4
  mockito: ^4.1.1
