name: ferry_cache
version: 0.1.0
description: Cache functionality for Ferry GraphQL client
homepage: https://github.com/gql-dart/ferry/tree/master/ferry_cache
repository: https://github.com/gql-dart/ferry

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  ferry_store: ^0.1.0
  rxdart: ^0.24.0
  normalize: ^0.1.1
  gql: ^0.12.0
  gql_exec: ^0.2.4

dev_dependencies:
  test: ^1.9.4

dependency_overrides:
  ferry_store:
    path: ../ferry_store
