name: gql_example_flutter
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  gql: ^0.12.0
  gql_link: ^0.2.1
  gql_http_link: ^0.2.2
  gql_exec: ^0.2.0
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  gql_client: ^0.0.1
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
  get_it: ^3.1.0
dev_dependencies:
  build_runner: ^1.0.0
  gql_pedantic: ^1.0.0
  gql_build: ^0.0.2
  flutter_test:
    sdk: flutter
dependency_overrides:
  gql:
    path: /Users/smkhalsa/dev/gql/gql/
  gql_link:
    path: /Users/smkhalsa/dev/gql/gql_link/
  gql_http_link:
    path: /Users/smkhalsa/dev/gql/gql_http_link/
  gql_exec:
    path: /Users/smkhalsa/dev/gql/gql_exec/
  gql_pedantic:
    path: /Users/smkhalsa/dev/gql/gql_pedantic/
  gql_build:
    path: /Users/smkhalsa/dev/gql/gql_build/
  gql_code_builder:
    path: /Users/smkhalsa/dev/gql/gql_code_builder/
  gql_client:
    path: /Users/smkhalsa/dev/gql_client/
flutter:
  uses-material-design: true
