name: Normalize Tests

on:
  push:
    paths:
      - "normalize/*"

jobs:
  build:
    defaults:
      run:
        shell: bash
        working-directory: normalize

    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run test
